In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv" #Important: Use RAW GitHub URL

df = pd.read_csv(url)

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
# sep parameter --> by default sep=',' so read_csv reads csv file by default .
#READING TSV FILE
df=pd.read_csv('Employee Dataset - TSV.txt',sep='\t')

In [ ]:
df

,Employee Name,Age,Last Working Day,Department,Education,Gender,Marital Status,Monthly Income,Years of Experience,Percent Salary Hike,Performance Rating
0,Jitesh,41,31-12-9999,Training,Masters,Male,Single,5993,8,11,3
1,Sanjit,49,31-12-9999,Sales,Masters,Male,Married,5130,1,23,4
2,John,37,31-12-9999,R&D,Doctorate,Male,Single,2090,6,15,3
3,Sandra,33,31-12-9999,Software Development,Undergraduate,Female,Married,2909,1,11,3
4,Madhu,27,31-12-9999,R&D,Masters,Male,Married,3468,9,12,3
5,Robert,32,31-12-9999,R&D,Masters,Male,Single,3068,0,13,3
6,Megan,59,31-12-9999,Software Development,Masters,Female,Married,2670,4,20,4
7,Matt,30,31-12-9999,R&D,Doctorate,Male,Divorced,2693,1,22,4
8,Will,38,01-03-2012,R&D,Doctorate,Male,Single,9526,0,21,4
9,George,36,31-12-9999,Software Development,Masters,NaN,Married,5237,6,13,3
10,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
11,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
12,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
13,Emma,29,31-12-9999,Software Development,Undergraduate,Female,Single,4193,0,12,3
14,Vin,31,31-12-9999,Software Development,Undergraduate,Male,NaN,2911,1,17,3
15,Richard,34,31-12-9999,Software Development,Undergraduate,Male,Divorced,2661,0,11,3
16,Clint,28,31-12-9999,Software Development,Undergraduate,Male,Single,2028,5,14,3
17,Kate,29,31-12-9999,Software Development,Undergraduate,Female,NaN,9980,1,11,3
18,Morgan,32,31-12-9999,Software Development,Undergraduate,Male,Divorced,3298,0,12,3
19,Mel,22,01-06-2014,Software Development,Masters,Male,Divorced,2935,1,13,3
20,Nicole,53,31-12-9999,Sales,Masters,Female,Married,15427,2,16,3
21,Angelina,38,31-12-9999,R&D,Doctorate,Female,Single,3944,5,11,3
22,Katherine,24,31-12-9999,Development,Masters,Female,Divorced,4011,0,18,3
23,Sean,36,31-12-9999,Sales,Masters,Male,Single,3407,7,23,4
24,Stella,34,31-12-9999,R&D,Doctorate,Female,Single,11994,0,11,3